// <auto-generated />
namespace CMS_Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addColumn_Wallet_Receiving_Money : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addColumn_Wallet_Receiving_Money));
        
        string IMigrationMetadata.Id
        {
            get { return "201903171418368_addColumn_Wallet_Receiving_Money"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
